"""
Open-source alternative to the paper's Power BI analytics layer (Section
III.D / Layer 4 in Fig. 1). Power BI itself is proprietary, so this module
produces the same class of deliverable — KPI cards, bottleneck
heatmaps/bars, approval-pipeline trends, predictive/trend charts — using
only open technology:

    1. A single self-contained HTML file (``results/dashboard/index.html``)
       built with Chart.js (MIT licensed, loaded from a public CDN by the
       *viewer's* browser — nothing is installed or downloaded in this
       repo). Open it directly in any browser; no server required.
    2. A SQLite export (``results/dashboard/ecm_analytics.db``) so the same
       data can be plugged straight into a full open-source BI platform —
       Metabase, Apache Superset or Grafana — if a team wants persistent,
       shared, multi-user dashboards instead of a static file.

Both are regenerated by ``scripts/05_generate_figures_tables.py``.
"""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import pandas as pd

from . import config as C

DASHBOARD_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ECM Digital Thread — Analytics Dashboard (open-source)</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>
<style>
  :root {{
    --bg: #0f1420; --card: #171d2b; --text: #e8ecf4; --muted: #9aa4b8;
    --accent: #4f8cff; --good: #35c98f; --bad: #ff6161; --border: #232b3d;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
    background: var(--bg); color: var(--text);
  }}
  header {{ padding: 24px 32px 8px; }}
  header h1 {{ margin: 0 0 4px; font-size: 22px; }}
  header p {{ margin: 0; color: var(--muted); font-size: 13px; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 16px; padding: 20px 32px; }}
  .card {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 16px 18px; }}
  .kpi .label {{ color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }}
  .kpi .value {{ font-size: 28px; font-weight: 700; margin-top: 6px; }}
  .kpi .delta {{ font-size: 12px; margin-top: 4px; }}
  .delta.good {{ color: var(--good); }}
  .delta.bad {{ color: var(--bad); }}
  .charts {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(420px, 1fr)); gap: 16px; padding: 0 32px 32px; }}
  .chart-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 16px; }}
  .chart-card h3 {{ margin: 0 0 12px; font-size: 14px; color: var(--muted); font-weight: 600; }}
  canvas {{ max-height: 320px; }}
  footer {{ padding: 16px 32px 40px; color: var(--muted); font-size: 12px; }}
  a {{ color: var(--accent); }}
</style>
</head>
<body>
<header>
  <h1>ECM Digital Thread — Analytics Dashboard</h1>
  <p>KPI monitoring, bottleneck detection, and traceability analytics for the
     Engineering Change Management (ECM) lifecycle in heavy machinery manufacturing.
     Computed from the toolkit's synthetic demonstration dataset.</p>
</header>

<div class="grid" id="kpi-grid"></div>

<div class="charts">
  <div class="chart-card"><h3>Change Cycle Time by Month (days)</h3><canvas id="cctChart"></canvas></div>
  <div class="chart-card"><h3>First-Pass Approval Rate Trend (%)</h3><canvas id="fparChart"></canvas></div>
  <div class="chart-card"><h3>Traceability Coverage Index Trend (%)</h3><canvas id="tciChart"></canvas></div>
  <div class="chart-card"><h3>Approval Pipeline Bottleneck Severity by Stage (First vs Latest Period)</h3><canvas id="bssChart"></canvas></div>
  <div class="chart-card"><h3>ECM Change Requests by Class</h3><canvas id="classChart"></canvas></div>
  <div class="chart-card"><h3>NLP Classifier — Precision / Recall / F1 by Class</h3><canvas id="nlpChart"></canvas></div>
</div>

<footer>
  ECM Digital Thread Toolkit · Full pipeline and source available in the project repository.
</footer>

<script>
const DATA = {data_json};

function kpiCard(label, value, delta, good) {{
  const div = document.createElement('div');
  div.className = 'card kpi';
  div.innerHTML = `<div class="label">${{label}}</div><div class="value">${{value}}</div>` +
    (delta !== undefined ? `<div class="delta ${{good ? 'good' : 'bad'}}">${{delta}}</div>` : '');
  return div;
}}

const grid = document.getElementById('kpi-grid');
DATA.kpi_cards.forEach(c => grid.appendChild(kpiCard(c.label, c.value, c.delta, c.good)));

const palette = ['#4f8cff', '#35c98f', '#ffb454', '#ff6161', '#b26bff', '#3ad0d0'];

new Chart(document.getElementById('cctChart'), {{
  type: 'line',
  data: {{ labels: DATA.months, datasets: [{{ label: 'CCT (days)', data: DATA.cct, borderColor: palette[0], tension: 0.35, fill: false }}] }},
  options: {{ plugins: {{ legend: {{ display: false }} }}, scales: {{ y: {{ beginAtZero: false }} }} }}
}});

new Chart(document.getElementById('fparChart'), {{
  type: 'line',
  data: {{ labels: DATA.months, datasets: [{{ label: 'FPAR (%)', data: DATA.fpar, borderColor: palette[1], tension: 0.35, fill: false }}] }},
  options: {{ plugins: {{ legend: {{ display: false }} }} }}
}});

new Chart(document.getElementById('tciChart'), {{
  type: 'line',
  data: {{ labels: DATA.months, datasets: [{{ label: 'TCI (%)', data: DATA.tci, borderColor: palette[2], tension: 0.35, fill: false }}] }},
  options: {{ plugins: {{ legend: {{ display: false }} }} }}
}});

new Chart(document.getElementById('bssChart'), {{
  type: 'bar',
  data: {{
    labels: DATA.stages,
    datasets: [
      {{ label: DATA.month1_label + ' (before)', data: DATA.bss_before, backgroundColor: palette[3] }},
      {{ label: DATA.month6_label + ' (after)', data: DATA.bss_after, backgroundColor: palette[0] }},
    ]
  }},
  options: {{ plugins: {{ legend: {{ position: 'bottom' }} }} }}
}});

new Chart(document.getElementById('classChart'), {{
  type: 'doughnut',
  data: {{ labels: DATA.class_labels, datasets: [{{ data: DATA.class_counts, backgroundColor: palette }}] }},
  options: {{ plugins: {{ legend: {{ position: 'right' }} }} }}
}});

new Chart(document.getElementById('nlpChart'), {{
  type: 'bar',
  data: {{
    labels: DATA.nlp_labels,
    datasets: [
      {{ label: 'Precision', data: DATA.nlp_precision, backgroundColor: palette[0] }},
      {{ label: 'Recall', data: DATA.nlp_recall, backgroundColor: palette[1] }},
      {{ label: 'F1', data: DATA.nlp_f1, backgroundColor: palette[2] }},
    ]
  }},
  options: {{ plugins: {{ legend: {{ position: 'bottom' }} }}, scales: {{ y: {{ min: 0, max: 1 }} }} }}
}});
</script>
</body>
</html>
"""


def _delta_str(before: float, after: float, lower_is_better: bool, baseline_label: str) -> tuple[str, bool]:
    pct = 100.0 * (after - before) / before if before else 0.0
    good = bool((pct < 0) if lower_is_better else (pct > 0))
    arrow = "↓" if pct < 0 else "↑"
    return f"{arrow} {abs(pct):.1f}% vs {baseline_label}", good


def build_dashboard_data(monthly_kpis: pd.DataFrame, bss_by_stage_month: pd.DataFrame,
                          class_counts: pd.Series, nlp_report: dict) -> dict:
    months = monthly_kpis["month"].tolist()
    before, after = monthly_kpis.iloc[0], monthly_kpis.iloc[-1]
    month_labels = [C.MONTH_LABELS[m - 1] if 1 <= m <= len(C.MONTH_LABELS) else f"Month {m}" for m in months]
    month1_label, month6_label = month_labels[0], month_labels[-1]

    def card(label, col, lower_is_better, suffix=""):
        delta, good = _delta_str(before[col], after[col], lower_is_better, month1_label)
        return {"label": label, "value": f"{after[col]:.1f}{suffix}", "delta": delta, "good": good}

    kpi_cards = [
        card("Change Cycle Time", "Change Cycle Time (days)", True, " days"),
        card("Approval Pending Rate", "Approval Pending Rate (%)", True, "%"),
        card("First-Pass Approval Rate", "First-Pass Approval Rate (%)", False, "%"),
        card("Traceability Coverage Index", "Traceability Coverage Index (%)", False, "%"),
        card("Documentation Error Rate", "Documentation Error Rate (%)", True, "%"),
        card("Change Propagation Index", "Change Propagation Index (%)", False, "%"),
    ]

    m1 = bss_by_stage_month[bss_by_stage_month["month"] == months[0]].set_index("workflow_stage")
    m6 = bss_by_stage_month[bss_by_stage_month["month"] == months[-1]].set_index("workflow_stage")
    stages = C.LIFECYCLE_STAGES

    labels_sorted = sorted(C.ECM_CLASS_PRIOR.keys())

    return {
        "months": month_labels,
        "month1_label": month1_label,
        "month6_label": month6_label,
        "cct": monthly_kpis["Change Cycle Time (days)"].tolist(),
        "fpar": monthly_kpis["First-Pass Approval Rate (%)"].tolist(),
        "tci": monthly_kpis["Traceability Coverage Index (%)"].tolist(),
        "stages": stages,
        "bss_before": [round(float(m1.loc[s, "BSS"]), 3) if s in m1.index else 0 for s in stages],
        "bss_after": [round(float(m6.loc[s, "BSS"]), 3) if s in m6.index else 0 for s in stages],
        "class_labels": class_counts.index.tolist(),
        "class_counts": class_counts.values.tolist(),
        "nlp_labels": labels_sorted,
        "nlp_precision": [round(nlp_report[l]["precision"], 3) for l in labels_sorted],
        "nlp_recall": [round(nlp_report[l]["recall"], 3) for l in labels_sorted],
        "nlp_f1": [round(nlp_report[l]["f1-score"], 3) for l in labels_sorted],
        "kpi_cards": kpi_cards,
    }


def write_html_dashboard(data: dict, out_path: Path | None = None) -> Path:
    out_path = out_path or (C.RESULTS_DASHBOARD_DIR / "index.html")
    html = DASHBOARD_HTML_TEMPLATE.format(data_json=json.dumps(data))
    out_path.write_text(html, encoding="utf-8")
    return out_path


def export_sqlite(df: pd.DataFrame, monthly_kpis: pd.DataFrame,
                   bss_by_stage_month: pd.DataFrame, out_path: Path | None = None) -> Path:
    """Export everything to a single SQLite file so any open-source BI tool
    (Metabase / Superset / Grafana with the SQLite plugin) can connect to it
    directly without re-running the Python pipeline."""
    out_path = out_path or (C.RESULTS_DASHBOARD_DIR / "ecm_analytics.db")
    if out_path.exists():
        out_path.unlink()
    conn = sqlite3.connect(out_path)
    df.to_sql("ecm_records", conn, index=False)
    monthly_kpis.to_sql("kpi_monthly", conn, index=False)
    bss_by_stage_month.to_sql("bottleneck_severity_by_stage", conn, index=False)
    conn.close()
    return out_path


if __name__ == "__main__":
    df = pd.read_csv(C.NLP_SCORED_CSV) if C.NLP_SCORED_CSV.exists() else pd.read_csv(C.RAW_DATASET_CSV)
    monthly_kpis = pd.read_csv(C.KPI_MONTHLY_CSV)
    bss = pd.read_csv(C.BSS_STAGE_CSV)
    class_counts = df["ecm_class"].value_counts()

    import json as _json
    nlp_report_path = C.RESULTS_TABLES_DIR / "table2_nlp_classification_report.json"
    nlp_report = _json.loads(nlp_report_path.read_text()) if nlp_report_path.exists() else {}

    data = build_dashboard_data(monthly_kpis, bss, class_counts, nlp_report)
    html_path = write_html_dashboard(data)
    db_path = export_sqlite(df, monthly_kpis, bss)
    print(f"Dashboard written to {html_path}")
    print(f"SQLite export written to {db_path}")
